export type Role = 'admin' | 'seller' | 'buyer';
export type Product = {id:string;slug:string;title:string;ko:string;category:string;price:number;image:string;seller:string;sellerId:string;format:string;details:string;detailsKo:string;status:'published'|'draft';rating:number};
export const products:Product[] = [
{id:'p1',slug:'make-good-work',title:'Make Good Work',ko:'좋은 작업을 만드는 법',category:'ebooks',price:24,image:'book',seller:'Studio North',sellerId:'studio-north',format:'PDF · 128 pages',details:'A practical field guide to finding your creative voice. Build a thoughtful practice with 12 chapters, creative exercises, and a printable workbook.',detailsKo:'나만의 창작 방식을 찾아가는 실용 가이드. 12개 챕터, 창작 연습과 인쇄 가능한 워크북으로 꾸준한 작업 습관을 만들어 보세요.',status:'published',rating:4.9},
{id:'p2',slug:'type-play-studio',title:'Type Play — Studio Kit',ko:'타입 플레이 — 스튜디오 키트',category:'design',price:39,image:'type',seller:'Studio North',sellerId:'studio-north',format:'Figma · 48 templates',details:'A considered collection of 48 editorial layouts, typography pairings, and presentation templates. Fully editable and ready for your next idea.',detailsKo:'편집 레이아웃, 타이포그래피 조합과 프레젠테이션 템플릿 48종. 모든 요소를 편집할 수 있어 다음 프로젝트에 바로 활용할 수 있습니다.',status:'published',rating:4.8},
{id:'p3',slug:'slow-summer-presets',title:'Slow Summer — Film Presets',ko:'슬로우 서머 — 필름 프리셋',category:'photo',price:19,image:'coast',seller:'James & June',sellerId:'james-june',format:'XMP / DNG · 12 presets',details:'Bring golden afternoons to every frame. Twelve film-inspired presets for Lightroom desktop and mobile, plus an easy installation guide.',detailsKo:'모든 사진에 황금빛 오후의 느낌을 더하세요. Lightroom 데스크톱·모바일용 필름 프리셋 12종과 설치 안내가 포함됩니다.',status:'published',rating:4.9},
{id:'p4',slug:'creative-practice-workbook',title:'The Creative Practice Workbook',ko:'크리에이티브 실천 워크북',category:'ebooks',price:12,image:'book',seller:'Studio North',sellerId:'studio-north',format:'PDF · 32 pages',details:'Thirty days of small prompts to make space for your best ideas. A companion workbook with printable planning sheets.',detailsKo:'좋은 아이디어를 위한 30일간의 작은 질문. 인쇄 가능한 계획표를 담은 실천 워크북입니다.',status:'published',rating:4.7},
{id:'p5',slug:'editorial-essentials',title:'Editorial Essentials',ko:'에디토리얼 에센셜',category:'design',price:29,image:'type',seller:'Form & Field',sellerId:'form-field',format:'Figma · 24 templates',details:'An adaptable editorial toolkit for independent brands: 24 clean layouts, style tokens, and quick-start instructions.',detailsKo:'독립 브랜드를 위한 편집 디자인 도구. 레이아웃 24종과 스타일 토큰, 빠른 시작 안내를 담았습니다.',status:'published',rating:4.8},
{id:'p6',slug:'coastal-stories',title:'Coastal Stories — Photo Collection',ko:'코스탈 스토리 — 사진 컬렉션',category:'photo',price:32,image:'coast',seller:'James & June',sellerId:'james-june',format:'JPG · 36 images',details:'Thirty-six coastal photographs with warm, cinematic tones for your moodboards and personal creative projects.',detailsKo:'따뜻한 영화적 색감의 해안 사진 36장. 무드보드와 개인 창작 프로젝트를 위한 컬렉션입니다.',status:'published',rating:4.9}
];
export const categories = [{id:'all',en:'All digital goods',ko:'전체 콘텐츠'},{id:'ebooks',en:'eBooks & guides',ko:'전자책 · 가이드'},{id:'design',en:'Design resources',ko:'디자인 리소스'},{id:'photo',en:'Photography',ko:'사진 · 프리셋'}];
export const baseMenus = [
{id:'overview',en:'Overview',ko:'대시보드'}, {id:'products',en:'Products',ko:'상품 관리'}, {id:'links',en:'Deep links',ko:'딥 링크 관리'}, {id:'orders',en:'Orders',ko:'주문 관리'}, {id:'customers',en:'Customers',ko:'구매자 관리'}, {id:'sellers',en:'Sellers',ko:'판매자 관리'}, {id:'payments',en:'Payments',ko:'결제 관리'}, {id:'settlements',en:'Settlements',ko:'정산 관리'}, {id:'coupons',en:'Coupons',ko:'쿠폰 관리'}, {id:'content',en:'Storefront',ko:'콘텐츠 관리'}, {id:'support',en:'Support',ko:'고객 문의'}, {id:'settings',en:'Settings',ko:'환경 설정'}
];
export type Order={id:string;productId:string;amount:number;date:string;buyer:string;source:string;status:'paid'|'refunded'};
export const initialOrders:Order[]=[{id:'RG-1048',productId:'p1',amount:24,date:'2026-09-15',buyer:'Alex Morgan',source:'instagram',status:'paid'},{id:'RG-1047',productId:'p2',amount:39,date:'2026-09-14',buyer:'Jamie Park',source:'direct',status:'paid'},{id:'RG-1046',productId:'p3',amount:19,date:'2026-09-14',buyer:'Taylor Lee',source:'newsletter',status:'paid'}];
export const menuGroups = [
{en:'Products',ko:'상품 관리',items:[['products','Product list','상품 목록'],['create','Add product','상품 등록'],['inventory','Inventory','재고 관리'],['categories','Categories','분류 관리'],['display','Product display','상품 진열 관리'],['collections','Collections','기획전 관리']]},
{en:'Orders',ko:'주문 관리',items:[['orders','All orders','전체 주문 목록'],['pending','Awaiting payment','입금전 관리'],['preparing','Preparing delivery','배송준비중'],['awaiting','Awaiting delivery','배송대기중'],['shipping','In transit','배송중'],['delivered','Delivered','배송완료'],['cancel','Cancellations','취소'],['exchange','Exchanges','교환'],['returns','Returns','반품']]},
{en:'Operators',ko:'운영자 관리',items:[['operators','Operators','운영자 관리'],['sellers','Sellers','판매자 관리'],['settlements','Settlements','정산 관리']]},
{en:'Members',ko:'회원 관리',items:[['members','Member list','회원 리스트'],['tiers','Member tiers','회원 등급 관리']]},
{en:'Messages',ko:'메시지 관리',items:[['notifications','Notifications','알림 관리'],['templates','Templates','템플릿 관리'],['sms','SMS billing','SMS 과금 관리']]},
{en:'Boards & posts',ko:'게시판/게시글 관리',items:[['boards','Boards','게시판 관리'],['posts','Posts','게시글 관리']]},
{en:'Design',ko:'디자인 관리',items:[['design','Design settings','디자인 관리'],['uploads','File uploader','파일 업로더'],['design-library','Design library','디자인 보관함'],['design-requests','Download requests','디자인 다운로드 요청 내역']]},
{en:'App creation',ko:'앱 제작 관리',items:[['app-form','Application form','앱 제작 신청서'],['app-list','Applications','앱 제작 신청 목록']]},
{en:'Promotions',ko:'프로모션 관리',items:[['coupons','Coupons','쿠폰 관리'],['coupon-create','Create coupon','쿠폰 생성']]},
{en:'Banners & popups',ko:'배너 팝업 관리',items:[['banners','Banner list','배너 팝업 목록'],['banner-create','Add banner','배너 팝업 등록']]},
{en:'Analytics',ko:'통계',items:[['sales','Sales','매출'],['analytics-products','Products · Items','상품 · 품목'],['analytics-categories','Products · Categories','상품 · 카테고리'],['deadstock','Products · Deadstock','상품 · 데드스탁'],['traffic','Traffic','트래픽 통계']]},
{en:'Settings',ko:'설정',items:[['settings','Preferences','환경설정'],['stores','Multiple stores','멀티쇼핑몰'],['links','Deep links','딥링크']]},
{en:'Activity',ko:'로그',items:[['logs','Log viewer','로그 뷰']]}
];
