const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
const output=ts.transpileModule(fs.readFileSync('lib/ringo/deep-links.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const moduleObject={exports:{}};vm.runInNewContext(output,{exports:moduleObject.exports,module:moduleObject,URL,Date});
const {buildDeepLink,resolveDeepLink,orderTotals,csvCell}=moduleObject.exports;
const p={id:'p1',slug:'example',sellerId:'studio-north',status:'published'};
const link={id:'test-link',productId:'p1',name:'Test',source:'instagram',medium:'social',campaign:'launch',destination:'checkout',language:'ko',expiresAt:'',status:'active'};
const url=buildDeepLink('https://ringo.example',p,link);
let r=resolveDeepLink(url,p,[link]);assert.equal(r.checkout,true);assert.equal(r.language,'ko');assert.equal(r.campaign,'launch');
assert.equal(resolveDeepLink(url.replace('seller=studio-north','seller=wrong'),p,[link]).error,'seller');
assert.equal(resolveDeepLink(url,p,[{...link,status:'paused'}]).error,'paused');
assert.equal(resolveDeepLink(url,p,[{...link,expiresAt:'2000-01-01'}]).error,'expired');
assert.equal(resolveDeepLink(url+'&expires=nonsense',p,[]).error,'invalid');
assert.equal(resolveDeepLink(url,p,[{...link,productId:'another'}]).error,'invalid');
assert.equal(resolveDeepLink(url.replace('utm_source=instagram','utm_source=tampered'),p,[link]).source,'instagram');
assert.equal(resolveDeepLink(url,p,[]).source,'instagram'); // portable seed-product demo links
assert.throws(()=>buildDeepLink('https://ringo.example',{...p,status:'draft'},link));
assert.throws(()=>buildDeepLink('https://ringo.example',p,{...link,productId:'wrong'}));
const totals=orderTotals([{status:'paid',amount:0.1},{status:'paid',amount:0.2},{status:'refunded',amount:100}]);assert.equal(totals.gross,.3);assert.equal(totals.net,.27);assert.equal(totals.paid,2);
assert.equal(csvCell('=SUM(A1)'), '"\'=SUM(A1)"');assert.equal(csvCell('a"b'),'"a""b"');
console.log('PASS: link routing, attribution, pause, expiry, seller mismatch, publication, money and CSV checks');
