'use client';
import type {ReactNode} from 'react';
import {ArrowUpRight,ArrowRight,Search,BookOpen,Palette,Camera,Download,Heart,Link2,Sparkles,Package,ShoppingBag,Check,Plus} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {categories,Product} from '@/lib/ringo/data';

type Props={t:(en:string,ko:string)=>string;products:Product[];filtered:Product[];category:string;setCategory:(v:string)=>void;q:string;setQ:(v:string)=>void;sort:string;setSort:(v:string)=>void;nav:(path:string)=>void;openLogin:()=>void;renderCard:(p:Product,i:number)=>ReactNode};
const price=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
export default function RingoHome({t,products,filtered,category,setCategory,q,setQ,sort,setSort,nav,openLogin,renderCard}:Props){
 const browse=(cat='all',query='')=>{setCategory(cat);setQ(query);document.getElementById('catalog')?.scrollIntoView({behavior:'smooth',block:'start'})};
 const book=products.find(p=>p.slug==='make-good-work')||products.find(p=>p.category==='ebooks');
 const design=products.find(p=>p.slug==='type-play-studio')||products.find(p=>p.category==='design');
 const photo=products.find(p=>p.slug==='slow-summer-presets')||products.find(p=>p.category==='photo');
 const creators=[{id:'studio-north',name:'Studio North',initial:'Sn.',specialty:t('Ideas into everyday practice.','아이디어를 일상의 작업으로.'),description:t('Thoughtful guides and useful tools for finding your own creative rhythm.','나만의 창작 리듬을 찾아가는 사려 깊은 가이드와 실용적인 도구.'),tag:t('WRITING & DESIGN','글쓰기 · 디자인'),theme:'ink'},{id:'james-june',name:'James & June',initial:'J&J',specialty:t('A different way of seeing.','세상을 바라보는 새로운 시선.'),description:t('Cinematic colors and coastal stories for the moments worth keeping.','오래 간직하고 싶은 순간을 위한 영화 같은 색감과 해안의 이야기.'),tag:t('PHOTOGRAPHY','사진 · 프리셋'),theme:'orange'},{id:'form-field',name:'Form & Field',initial:'F/f',specialty:t('Make room for good design.','좋은 디자인을 위한 여유.'),description:t('Flexible editorial systems that give your next project a confident start.','다음 프로젝트의 자신 있는 시작을 돕는 유연한 편집 디자인 시스템.'),tag:t('DESIGN RESOURCES','디자인 리소스'),theme:'blue'}];
 return <main className="ringo-home">
 <section className="rh-hero rh-shell"><div className="rh-hero-copy"><div className="rh-kicker"><span className="rh-kicker-mark"><Sparkles size={14}/></span>{t('A MARKETPLACE FOR CURIOUS MINDS','호기심 많은 당신을 위한 디지털 편집숍')}</div><h1>{t('Good things.','좋은 콘텐츠.')}<br/>{t('Great ideas.','멋진 아이디어.')}<br/><em>{t('All yours.','이제, 당신의 것.')}</em></h1><p>{t('A new skill. A fresh perspective. A little creative spark. Find digital goods that help you make something wonderful.','새로운 배움, 신선한 시선, 작은 창작의 불씨. 멋진 무언가를 만들도록 도와줄 디지털 콘텐츠를 만나보세요.')}</p><div className="rh-hero-actions"><Button onClick={()=>browse()}>{t('Explore digital goods','디지털 콘텐츠 둘러보기')}<ArrowUpRight size={19}/></Button><button className="rh-text-link" onClick={()=>document.getElementById('ringo-edit')?.scrollIntoView({behavior:'smooth'})}>{t('Meet the Ringo edit','링고 에디터 추천')}<ArrowRight size={16}/></button></div><div className="rh-hero-foot"><div className="rh-tiny-logo">r.</div><div><strong>{t('Made by people. Picked with purpose.','사람이 만들고, 이유 있게 고른 콘텐츠.')}</strong><span>{t('eBooks, creative assets & things you’ll love using.','전자책부터 디자인 에셋까지, 즐겁게 사용할 것들.')}</span></div></div></div><div className="rh-hero-gallery"><span className="rh-gallery-note">{t('THE RINGO EDIT','링고 에디터 추천')}<span>01 — 03</span></span>{book&&<button className="rh-hero-cover" onClick={()=>nav('/p/'+book.slug)}><img src={'/images/'+book.image+'.webp'} alt={t(book.title,book.ko)} fetchPriority="high"/><span className="rh-cover-badge"><BookOpen size={14}/>{t('A fresh perspective','새로운 관점')}</span><div className="rh-cover-caption"><div><small>{book.seller}</small><strong>{t(book.title,book.ko)}</strong></div><span className="rh-circle"><ArrowUpRight size={21}/></span></div></button>}{design&&<button className="rh-side-cover rh-side-design" onClick={()=>nav('/p/'+design.slug)}><img src={'/images/'+design.image+'.webp'} alt={t(design.title,design.ko)}/><span>{t('Create something bold.','과감하게, 새롭게.')}<ArrowUpRight size={18}/></span></button>}{photo&&<button className="rh-side-cover rh-side-photo" onClick={()=>nav('/p/'+photo.slug)}><img src={'/images/'+photo.image+'.webp'} alt={t(photo.title,photo.ko)}/><span>{t('See it differently.','다르게 바라보기.')}<ArrowUpRight size={18}/></span></button>}<div className="rh-gallery-bottom"><span>{t('SMALL DOWNLOADS. BIG POSSIBILITIES.','작은 다운로드. 커다란 가능성.')}</span><span>↓</span></div></div></section>
 <div className="rh-promise"><div className="rh-shell"><span><Download size={17}/>{t('Digital. Ready when you are.','필요한 순간, 바로 디지털로.')}</span><i/><span><Heart size={17}/>{t('Independent minds, original work.','독립적인 창작자의 오리지널 콘텐츠.')}</span><i/><span><Link2 size={17}/>{t('One link to your next great find.','링크 하나로 만나는 새로운 발견.')}</span></div></div>
 <section className="rh-explore rh-shell"><div className="rh-section-top"><p className="rh-kicker">{t('FOLLOW YOUR CURIOSITY','당신의 호기심을 따라')}</p><p>{t('What will you make next?','다음에는 무엇을 만들어 볼까요?')}</p></div><div className="rh-categories">{[{id:'ebooks',icon:BookOpen,title:t('Read. Learn. Grow.','읽고, 배우고, 성장하기.'),desc:t('eBooks & practical guides','전자책 · 실용 가이드'),style:'coral'},{id:'design',icon:Palette,title:t('Make your mark.','나만의 색을 더하기.'),desc:t('Design kits & templates','디자인 키트 · 템플릿'),style:'lilac'},{id:'photo',icon:Camera,title:t('Capture a feeling.','순간의 감성을 담기.'),desc:t('Photography & presets','사진 · 프리셋'),style:'cyan'}].map(c=><button className={'rh-category '+c.style} key={c.id} onClick={()=>browse(c.id)}><span className="rh-category-icon"><c.icon size={25} strokeWidth={1.4}/></span><span><strong>{c.title}</strong><small>{c.desc}</small></span><ArrowUpRight size={22}/></button>)}</div></section>
 <section id="catalog" className="rh-catalog rh-shell"><div className="rh-section-heading"><div><p className="rh-kicker">{t('GOOD FINDS, ALL IN ONE PLACE','좋은 발견을 한곳에')}</p><h2>{t('Your next favorite is here.','마음에 드는 다음 콘텐츠.')}</h2></div><p>{t('Thoughtfully made. Ready to make it yours.','정성스럽게 만든 콘텐츠, 당신의 시작을 기다립니다.')}</p></div><div className="rh-catalog-toolbar"><div className="rh-filter-tabs">{categories.map(c=><button key={c.id} aria-pressed={category===c.id} className={category===c.id?'selected':''} onClick={()=>setCategory(c.id)}>{t(c.en,c.ko)}{c.id==='all'&&<span>{products.length}</span>}</button>)}</div><div className="rh-search"><Search size={17}/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder={t('Find your inspiration…','영감을 찾아보세요…')} aria-label={t('Search digital goods','디지털 콘텐츠 검색')}/></div></div><div className="rh-results"><span aria-live="polite">{filtered.length} {t('digital goods to explore','개의 디지털 콘텐츠')}</span><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label={t('Sort products','상품 정렬')}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="featured">{t('Curated for you','추천순')}</SelectItem><SelectItem value="low">{t('Price: low to high','가격 낮은 순')}</SelectItem><SelectItem value="high">{t('Price: high to low','가격 높은 순')}</SelectItem></SelectContent></Select></div><div className="product-grid">{filtered.map((p,i)=>renderCard(p,i))}</div>{!filtered.length&&<div className="rh-empty"><Search size={32}/><h3>{t('Let’s try a different idea.','다른 콘텐츠를 찾아볼까요?')}</h3><p>{t('No digital goods match these filters.','현재 조건에 맞는 콘텐츠가 없습니다.')}</p><Button variant="outline" onClick={()=>browse()}>{t('Clear filters','검색 조건 초기화')}</Button></div>}<div className="rh-catalog-end"><span>{t('A small collection. A world of inspiration.','작은 컬렉션 속, 무한한 영감.')}</span><Sparkles size={18}/></div></section>
 {design&&<section id="ringo-edit" className="rh-editorial rh-shell"><div className="rh-editorial-inner"><button className="rh-editorial-image" onClick={()=>nav('/p/'+design.slug)} aria-label={t(design.title,design.ko)}><img src={'/images/'+design.image+'.webp'} alt={t(design.title,design.ko)} loading="lazy"/><span>{t('THE CREATIVE TOOLKIT','창작자를 위한 도구 상자')}<ArrowUpRight size={20}/></span></button><div className="rh-editorial-copy"><p className="rh-kicker"><Sparkles size={15}/>{t('IN THE SPOTLIGHT','에디터가 주목한 콘텐츠')}</p><h2>{t('Less blank canvas.','빈 화면의 고민은 줄이고.')}<br/><em>{t('More possibility.','가능성은 더 크게.')}</em></h2><p>{t('Give your next idea a head start. A considered collection of layouts, typography, and design details — ready for your own creative twist.','다음 아이디어를 조금 더 쉽게 시작하세요. 세심하게 구성한 레이아웃과 타이포그래피, 디자인 디테일에 당신만의 생각을 더해보세요.')}</p><ul><li><Check size={17}/>{t('Editable layouts for your next project','다음 프로젝트에 맞게 편집하는 레이아웃')}</li><li><Check size={17}/>{t('A cohesive starting point for your ideas','아이디어를 일관성 있게 담는 시작점')}</li><li><Check size={17}/>{t('Created by '+design.seller,design.seller+'의 창작 리소스')}</li></ul><div className="rh-editorial-cta"><Button onClick={()=>nav('/p/'+design.slug)}>{t('Explore the toolkit','디자인 키트 살펴보기')}<ArrowUpRight size={18}/></Button><span>{price(design.price)} <small>USD</small></span></div></div></div></section>}
 <section className="rh-creators rh-shell" id="creators"><div className="rh-section-heading"><div><p className="rh-kicker">{t('BEHIND EVERY GOOD FIND','좋은 콘텐츠 뒤에는')}</p><h2>{t('Real ideas. Independent minds.','아이디어를 만드는 사람들.')}</h2></div><p>{t('Meet the studios in our demo collection.','링고 데모 컬렉션 속 스튜디오를 만나보세요.')}</p></div><div className="rh-creator-grid">{creators.map(c=><article className="rh-creator" key={c.id}><div className="rh-creator-top"><span className={'rh-studio-monogram '+c.theme}>{c.initial}</span><span className="rh-studio-tag">{c.tag}</span></div><h3>{c.name}</h3><strong>{c.specialty}</strong><p>{c.description}</p><div className="rh-creator-bottom"><span>{products.filter(p=>p.sellerId===c.id).length} {t('digital goods','개의 콘텐츠')}</span><button onClick={()=>browse('all',c.name)} aria-label={t('Explore '+c.name,c.name+' 상품 보기')}><ArrowUpRight size={21}/></button></div></article>)}</div></section>
 <section className="rh-how rh-shell"><div className="rh-how-intro"><p className="rh-kicker">{t('FROM FOUND TO YOURS','발견부터 나의 콘텐츠가 되기까지')}</p><h2>{t('A few clicks.','몇 번의 클릭.')}<br/><em>{t('A fresh start.','새로운 시작.')}</em></h2><p>{t('Try the journey with a demo purchase.','테스트 구매로 링고의 이용 과정을 확인해 보세요.')}</p></div><div className="rh-steps">{[{n:'01',icon:Search,title:t('Find your spark','영감을 발견하세요'),text:t('Browse a collection, explore a creator, or search for your next idea.','컬렉션을 둘러보고 크리에이터의 작업 속에서 다음 아이디어를 찾아보세요.')},{n:'02',icon:ShoppingBag,title:t('Make it yours','마음에 드는 콘텐츠를 선택하세요'),text:t('Open a product and complete a demo checkout with the buyer test account.','상품 상세를 확인하고 구매자 테스트 계정으로 데모 결제를 진행하세요.')},{n:'03',icon:Download,title:t('Let’s make something','이제, 시작해 볼까요'),text:t('Your sample download is waiting in your library. No real payment required.','라이브러리에 준비된 샘플 파일을 다운로드하세요. 실제 결제는 발생하지 않습니다.')}].map(s=><div className="rh-step" key={s.n}><div><span>{s.n}</span><s.icon size={20} strokeWidth={1.4}/></div><h3>{s.title}</h3><p>{s.text}</p></div>)}</div></section>
 <section className="rh-faq rh-shell"><div><p className="rh-kicker">{t('A FEW GOOD ANSWERS','궁금한 점을 모았어요')}</p><h2>{t('Curious about Ringo?','링고가 더 궁금한가요?')}</h2><p>{t('A little clarity before your next discovery.','새로운 발견을 시작하기 전, 알아두면 좋은 이야기.')}</p></div><Accordion type="single" collapsible className="rh-faq-list">{[{q:t('What can I find on Ringo?','링고에서는 어떤 콘텐츠를 만날 수 있나요?'),a:t('Ringo brings together digital eBooks, practical guides, editable design resources, and photography presets. The current collection uses sample products and AI-generated artwork.','전자책, 실용 가이드, 편집 가능한 디자인 리소스와 사진 프리셋을 만날 수 있습니다. 현재 컬렉션은 생성형 이미지와 예시 상품으로 구성되어 있습니다.')},{q:t('How do I access my purchases?','구매한 콘텐츠는 어디에서 확인하나요?'),a:t('Choose the buyer test login, open a product and complete the demo checkout. Your library will contain a sample TXT download. Full commercial product files are not included in this demo.','구매자 테스트 로그인 후 상품에서 데모 결제를 완료하면 라이브러리에 샘플 TXT 다운로드가 추가됩니다. 실제 판매용 원본 콘텐츠는 이 데모에 포함되어 있지 않습니다.')},{q:t('Can I share a product with a direct link?','상품을 링크로 바로 공유할 수 있나요?'),a:t('Yes. Use Share on a product page or Deep links in the seller workspace. The link includes the product, seller and campaign. Newly added demo products are only stored in your current browser.','네. 상품 상세의 공유 또는 판매자 화면의 딥 링크 메뉴를 이용하세요. 상품·판매자·캠페인 정보가 링크에 포함됩니다. 새로 등록한 데모 상품은 현재 브라우저에만 저장됩니다.')},{q:t('How can I start selling?','판매자로 시작하려면 어떻게 하나요?'),a:t('Open Test login and choose Seller. You can add a digital product, edit its details, set it to published and create a share link. Real file uploads, payments and payouts will be connected before launch.','테스트 로그인에서 판매자를 선택하세요. 디지털 상품을 등록하고 상세 내용을 수정한 뒤 공개 상태로 설정해 공유 링크를 만들 수 있습니다. 실제 파일 업로드·결제·정산은 출시 전 연결할 예정입니다.')}].map((f,i)=><AccordionItem key={f.q} value={'faq-'+i}><AccordionTrigger>{f.q}</AccordionTrigger><AccordionContent>{f.a}</AccordionContent></AccordionItem>)}</Accordion></section>
 <section className="rh-seller rh-shell"><div className="rh-seller-inner"><div><p className="rh-kicker">{t('FOR THE MAKERS, THINKERS & DOERS','만들고, 생각하고, 실천하는 당신에게')}</p><h2>{t('You make the good stuff.','좋은 콘텐츠를 만들어 주세요.')}<br/><em>{t('We make room for it.','링고가 함께할게요.')}</em></h2><p>{t('Turn what you know into something worth sharing. Your digital storefront starts with one good idea.','당신의 지식과 경험을 나누고 싶은 콘텐츠로. 좋은 아이디어 하나로 디지털 스토어를 시작하세요.')}</p><Button onClick={openLogin}>{t('Explore selling on Ringo','링고에서 판매 시작하기')}<ArrowUpRight size={20}/></Button></div><div className="rh-seller-note"><span className="rh-seller-symbol">ringo<span>®</span></span><div><span>01</span>{t('Create something useful.','쓸모 있는 콘텐츠를 만들고.')}</div><div><span>02</span>{t('Share it with your people.','당신의 사람들에게 공유하고.')}</div><div><span>03</span>{t('Make your next move.','다음 가능성을 열어보세요.')}</div><small>{t('YOUR IDEAS BELONG HERE.','당신의 아이디어가 머무는 곳.')}</small></div></div></section>
 </main>;
}
