'use client';
import {createId} from '@/lib/ringo/ids';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {categories,Product} from '@/lib/ringo/data';
import {saveAsset} from '@/lib/ringo/assets';
import {toast} from 'sonner';
export default function ProductEditor({product,t,onSave,onClose}:{product:Product|null;t:(en:string,ko:string)=>string;onSave:(p:Product)=>void;onClose:()=>void}){
 const [category,setCategory]=useState(product?.category||'ebooks');const [saving,setSaving]=useState(false);
 return <Dialog open onOpenChange={v=>{if(!v&&!saving)onClose()}}><DialogContent className="product-form ro-product-editor"><DialogTitle>{product?t('Edit digital product','디지털 상품 수정'):t('Create a product','상품 등록')}</DialogTitle><DialogDescription>{t('Add the details your buyers need. Uploaded files are stored in this browser only (25 MB limit).','구매자에게 필요한 정보를 입력하세요. 업로드 파일은 이 브라우저에만 저장됩니다(최대 25MB).')}</DialogDescription><form onSubmit={async e=>{e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);try{const price=Number(f.get('price'));if(!Number.isFinite(price)||price<0)throw new Error(t('Enter a valid price.','올바른 가격을 입력하세요.'));const id=product?.id||'p-'+createId();const file=f.get('asset') as File;const next:Product={id,slug:product?.slug||'item-'+id.slice(2),seller:product?.seller||'Studio North',sellerId:product?.sellerId||'studio-north',title:String(f.get('title')).trim(),ko:String(f.get('ko')).trim(),price:Math.round(price*100)/100,category,status:f.get('status') as Product['status'],image:String(f.get('image')),details:String(f.get('details')),detailsKo:String(f.get('detailsKo')),format:String(f.get('format')),rating:product?.rating||0,delivery:category==='courses'?'course':category==='advertising'?'service':category==='collections'?'collection':'download',deliveryDays:category==='advertising'?Number(f.get('days')):undefined,lessons:category==='courses'?String(f.get('lessons')).split('\n').map(x=>x.trim()).filter(Boolean):undefined,assetName:product?.assetName,assetSize:product?.assetSize};if(!next.title||!next.ko)throw new Error(t('Both titles are required.','영문·한글 상품명을 모두 입력하세요.'));if(file?.size){await saveAsset(id,file);next.assetName=file.name;next.assetSize=file.size;}onSave(next);onClose();toast.success(t('Product saved.','상품을 저장했습니다.'));}catch(err){toast.error(err instanceof Error?err.message:'Unable to save');}finally{setSaving(false)}}}>
 <label>{t('Content type','콘텐츠 유형')}<Select name="category" value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{categories.filter(c=>c.id!=='all').map(c=><SelectItem key={c.id} value={c.id}>{t(c.en,c.ko)}</SelectItem>)}</SelectContent></Select></label><div className="form-columns"><label>{t('English title','영문 상품명')}<Input name="title" required maxLength={120} defaultValue={product?.title}/></label><label>{t('Korean title','한글 상품명')}<Input name="ko" required maxLength={120} defaultValue={product?.ko}/></label></div><div className="form-columns"><label>{t('Price · USD','판매가 · USD')}<Input name="price" type="number" min="0" max="99999" step="0.01" defaultValue={product?.price??19} required/></label><label>{t('Publication','판매 상태')}<Select name="status" defaultValue={product?.status||'draft'}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">{t('Draft','임시저장')}</SelectItem><SelectItem value="published">{t('Published','판매중')}</SelectItem></SelectContent></Select></label></div><label>{t('What is included?','구성 안내')}<Input name="format" defaultValue={product?.format||'PDF · Digital download'} required maxLength={100}/></label><label>{t('Cover artwork','표지 이미지')}<Select name="image" defaultValue={product?.image||'book'}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[['book','eBook','전자책'],['type','Design resource','디자인 자료'],['coast','Photography','사진'],['banner-books','eBook collection','전자책 컬렉션'],['banner-course','Course','강의'],['banner-design','Advertising & design','광고 · 디자인']].map(([id,en,ko])=><SelectItem key={id} value={id}>{t(en,ko)}</SelectItem>)}</SelectContent></Select></label><label>{t('English description','영문 상세 설명')}<Textarea name="details" required maxLength={3000} defaultValue={product?.details}/></label><label>{t('Korean description','한글 상세 설명')}<Textarea name="detailsKo" required maxLength={3000} defaultValue={product?.detailsKo}/></label>{category==='courses'&&<label>{t('Curriculum · one lesson per line','강의 목차 · 한 줄에 한 강의')}<Textarea name="lessons" required defaultValue={product?.lessons?.join('\n')||'Introduction / 시작하기\nCreative practice / 실습하기\nYour next project / 다음 프로젝트'} maxLength={2500}/></label>}{category==='advertising'&&<label>{t('Delivery time · days','제작 소요일')}<Input type="number" name="days" min="1" max="90" defaultValue={product?.deliveryDays||5} required/></label>}<label>{t('Digital file · optional in demo','디지털 파일 · 데모에서 선택 사항')}<Input type="file" name="asset" accept=".pdf,.txt,.zip,.epub,.mp4,.png,.jpg,.webp"/>{product?.assetName&&<small>{t('Current file: ','등록 파일: ')}{product.assetName}</small>}<small>{t('Without a file, buyers receive the clearly labeled sample preview.','파일을 등록하지 않으면 구매자는 데모로 표시된 샘플 미리보기를 받습니다.')}</small></label><Button type="submit" disabled={saving}>{saving?t('Saving…','저장 중…'):t('Save product','상품 저장')}</Button></form></DialogContent></Dialog>
}
