'use client';
import {useState} from 'react';
import {Mail,ShieldCheck,Store,ShoppingBag,ArrowRight,LockKeyhole} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import type {Role} from '@/lib/ringo/data';
export default function RingoAuth({open,onOpenChange,t,onDemo}:{open:boolean;onOpenChange:(v:boolean)=>void;t:(en:string,ko:string)=>string;onDemo:(r:Role)=>void}){
 const [mode,setMode]=useState('login');const [emailForm,setEmailForm]=useState(false);
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="ringo-auth"><DialogTitle><span className="brand"><img src="/favicon.svg" alt=""/>ringo</span></DialogTitle><DialogDescription>{t('Your next idea starts here.','다음 아이디어가 시작되는 곳.')}</DialogDescription><Tabs value={mode} onValueChange={v=>{setMode(v);setEmailForm(false)}}><TabsList className="auth-tabs"><TabsTrigger value="login">{t('Log in','로그인')}</TabsTrigger><TabsTrigger value="signup">{t('Sign up','회원가입')}</TabsTrigger></TabsList></Tabs><h2>{mode==='login'?t('Welcome back.','다시 만나 반가워요.'):t('Make room for your next idea.','다음 아이디어를 위한 시작.')}</h2><div className="social-auth"><Button type="button" variant="outline" disabled><span className="google-letter">G</span>{mode==='login'?t('Continue with Google','Google 로그인'):t('Sign up with Google','Google 회원가입')}<small>{t('Coming soon','연동 예정')}</small></Button><Button type="button" variant="outline" disabled><span className="facebook-letter">f</span>{mode==='login'?t('Continue with Facebook','Facebook 로그인'):t('Sign up with Facebook','Facebook 회원가입')}<small>{t('Coming soon','연동 예정')}</small></Button></div><div className="auth-divider"><span>{t('or','또는')}</span></div><Button variant="outline" className="email-option" onClick={()=>setEmailForm(!emailForm)} aria-expanded={emailForm}><Mail size={18}/>{mode==='login'?t('Log in with email','이메일 로그인'):t('Sign up with email','이메일 회원가입')}</Button>{emailForm&&<div className="auth-email-fields">{mode==='signup'&&<label>{t('Name','이름')}<Input disabled placeholder={t('Your name','이름을 입력하세요')}/></label>}<label>{t('Email','이메일')}<Input type="email" disabled placeholder="you@example.com"/></label><label>{t('Password','비밀번호')}<Input type="password" disabled placeholder="••••••••"/></label><Button disabled>{mode==='login'?t('Log in with email','이메일로 로그인'):t('Create account','이메일로 회원가입')}</Button><p><LockKeyhole size={14}/>{t('Email authentication will be enabled when the account server is connected. No credentials are collected in this preview.','계정 서버 연결 후 이메일 인증을 사용할 수 있습니다. 현재 화면에서는 인증 정보를 수집하지 않습니다.')}</p></div>}<div className="auth-demo-section"><div><span>{t('Explore the demo','테스트 로그인')}</span><small>{t('No account needed','계정 없이 바로 확인')}</small></div>{([{id:'admin',icon:ShieldCheck,en:'Super administrator test login',ko:'최고 관리자 테스트 로그인'},{id:'seller',icon:Store,en:'Seller test login',ko:'판매자 테스트 로그인'},{id:'buyer',icon:ShoppingBag,en:'Buyer test login',ko:'구매자 테스트 로그인'}] as const).map(r=><button key={r.id} onClick={()=>onDemo(r.id)}><r.icon size={18}/><span>{t(r.en,r.ko)}</span><ArrowRight size={16}/></button>)}</div><p className="auth-disclaimer">{t('Demo purchases do not charge money. Demo data stays in this browser.','테스트 구매는 실제 과금되지 않으며 데모 데이터는 이 브라우저에 저장됩니다.')}</p></DialogContent></Dialog>
}
