'use client';
import {useEffect,useState} from 'react';
import {Carousel,CarouselContent,CarouselItem,type CarouselApi} from '@/components/ui/carousel';
import {Button} from '@/components/ui/button';
import {ArrowLeft,ArrowRight,ArrowUpRight,Sparkles} from 'lucide-react';
export default function RingoHero({t,browse}:{t:(e:string,k:string)=>string;browse:(c:string)=>void}){
 const [api,setApi]=useState<CarouselApi>();const [current,setCurrent]=useState(0);
 useEffect(()=>{if(!api)return;const select=()=>setCurrent(api.selectedScrollSnap());select();api.on('select',select);return()=>{api.off('select',select)}},[api]);
 const slides=[{image:'books-v2.webp',category:'ebooks',tag:'THE NEXT CHAPTER',tk:'읽고, 배우고, 확장하는 시간',title:'Small downloads.',ko:'작은 콘텐츠,',accent:'Big possibilities.',ak:'더 큰 가능성.',body:'Ideas worth keeping. Stories worth sharing. Discover your next favorite eBook on Ringo.',bk:'간직하고 싶은 아이디어와 나누고 싶은 이야기를 링고에서 만나보세요.',cta:'Find your next read',ck:'전자책 둘러보기'},{image:'course-v2.webp',category:'courses',tag:'LEARN SOMETHING WONDERFUL',tk:'배움이 가능성이 되는 곳',title:'A new skill.',ko:'오늘의 배움이',accent:'A whole new you.',ak:'내일의 가능성으로.',body:'Learn from independent creators and turn a little curiosity into your next great idea.',bk:'독립 크리에이터와 함께 호기심을 새로운 기술과 아이디어로 키워보세요.',cta:'Explore courses',ck:'강의 둘러보기'},{image:'design-v2.webp',category:'collections',tag:'MADE FOR YOUR NEXT BIG IDEA',tk:'다음 아이디어를 위한 영감',title:'Create your thing.',ko:'좋은 아이디어를',accent:'Share it with Ringo.',ak:'세상과 연결하세요.',body:'Digital tools, creative services and curated collections. Everything to bring your vision to life.',bk:'디지털 도구와 창작 서비스, 엄선한 컬렉션으로 당신의 아이디어를 완성해 보세요.',cta:'Discover collections',ck:'기획전 둘러보기'}];
 return <section className="rh-banner rh-shell"><Carousel setApi={setApi} opts={{loop:true}} aria-label={t('Ringo highlights','링고 추천 배너')}><CarouselContent>{slides.map((s,i)=><CarouselItem key={s.image}><div className={'rh-slide slide-'+i} inert={i!==current}><div className="rh-slide-copy"><p className="rh-kicker"><Sparkles size={15}/>{t(s.tag,s.tk)}</p><h1>{t(s.title,s.ko)}<br/><em>{t(s.accent,s.ak)}</em></h1><p>{t(s.body,s.bk)}</p><Button onClick={()=>browse(s.category)}>{t(s.cta,s.ck)}<ArrowUpRight size={18}/></Button><span className="rh-slide-sign">ringo® · DIGITAL GOODS. HUMAN CREATIVITY.</span></div><div className="rh-slide-art"><img src={'/images/banner-'+s.image} alt={t(['Art books with warm sculptural shapes','Creative learning workspace','Colorful digital design collection'][i],['책과 종이 오브제가 놓인 따뜻한 스튜디오','창작과 배움을 위한 작업 공간','컬러와 형태를 탐구하는 디자인 스튜디오'][i])} fetchPriority={i===0?'high':'auto'}/><span>RINGO SELECTS · 0{i+1}</span></div></div></CarouselItem>)}</CarouselContent><div className="rh-slider-controls"><span aria-live="polite">0{current+1} <span>/ 03</span></span><div>{slides.map((s,i)=><button key={s.image} className={current===i?'active':''} aria-label={t('Show banner '+(i+1),(i+1)+'번 배너 보기')} aria-current={current===i?'true':undefined} onClick={()=>api?.scrollTo(i)}/>)}</div><div><Button variant="ghost" size="icon" aria-label={t('Previous banner','이전 배너')} onClick={()=>api?.scrollPrev()}><ArrowLeft/></Button><Button variant="ghost" size="icon" aria-label={t('Next banner','다음 배너')} onClick={()=>api?.scrollNext()}><ArrowRight/></Button></div></div></Carousel></section>
}
